image:
  file: .gitpod/Dockerfile

tasks:
  - name: Nuxt/Storybook
    command: |
      gp sync-await npm
      npx nuxt storybook --ci

  - name: Nuxt/Druxt
    init: |
      npm i
      gp sync-done npm
    command: npm run dev

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - editorconfig.editorconfig
    - gruntfuggly.todo-tree
    - octref.vetur

ports:
  - port: 3000
    visibility: public
  - port: 3003
    visibility: public

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: true
