docker-compose-yaml: docker-compose.backend.yml

project: druxtjs-org-demo-umami

tasks:
  post-rollout:
    - run:
        name: drupal install
        command: >-
          DRUPAL_DB_URL="mysql://${MARIADB_USERNAME}:${MARIADB_PASSWORD}@${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_DATABASE}"
          .devtools/provision
        service: cli

    - run:
        name: drush user:login
        command: drush user:login
        service: cli

environments:
  staging/backend:
    routes:
      - nginx:
          - api.staging.umami.demo.druxtjs.org
  production/backend:
    routes:
      - nginx:
          - api.umami.demo.druxtjs.org
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
