docker-compose-yaml: docker-compose.yml

project: demo-druxtjs-org

environments:
  main:
    routes:
      - app:
          - demo.druxtjs.org
      - storybook:
          - storybook.demo.druxtjs.org
