version: '2.3'

services:
  app:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: .docker/Dockerfile.app
      args:
        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
        GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
        OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
    labels:
      lagoon.type: node
      lando.type: node
    environment:
      LAGOON_LOCALDEV_HTTP_PORT: 3000
      LAGOON_ROUTE: http://demo-druxtjs-org.docker.amazee.io

  storybook:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: .docker/Dockerfile.storybook
      args:
        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
        GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
        OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
    labels:
      lagoon.type: node
      lando.type: node
    environment:
      LAGOON_LOCALDEV_HTTP_PORT: 3000
      LAGOON_ROUTE: http://storybook-demo-druxtjs-org.docker.amazee.io

networks:
  amazeeio-network:
    external: true
