#!/bin/bash

## Description: Install Drupal
## Usage: drupal-install
## Example: "ddev drupal-install"

# Install composer dependencies.
composer install

# Install Drupal using the Umami demo profile via TomeSync.
drush -y tome:install

# Index search results.
drush search-api:index
